//
// Created by sirin on 2025/11/30.
//

#ifndef H723VG_V2_FREERTOS_BSP_I2C_H
#define H723VG_V2_FREERTOS_BSP_I2C_H

#include "stm32h7xx_hal.h"
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================
 * D-Cache / mem_sections compatibility (same style as bsp_spi)
 * ============================================================ */
#ifdef OMNIX_FEATURE_MPU_DCACHE

#if __has_include("mem_sections.h")
#include "mem_sections.h"
/**
 * @brief Attribute for I2C DMA buffers.
 *
 * Put static DMA buffers into non-cacheable section to avoid
 * manual cache maintenance when D-Cache is enabled.
 */
#define BSP_I2C_DMA_SEC  SEC_DMA_NC_BUF

#else
/* D-Cache is enabled BUT mem_sections.h is not found.
 * BSP_I2C_DMA_SEC will be empty: DMA buffers remain cacheable.
 * Emit a compile-time INFO so you do not forget to handle cache.
 */
#define BSP_I2C_DMA_SEC

#if defined(__GNUC__) || defined(__clang__)
#pragma message "[bsp_i2c] OMNIX_FEATURE_MPU_DCACHE defined but mem_sections.h not found; BSP_I2C_DMA_SEC is empty (DMA buffers are cacheable, remember to maintain D-Cache)."
#else
#warning "bsp_i2c: OMNIX_FEATURE_MPU_DCACHE defined but mem_sections.h not found; BSP_I2C_DMA_SEC is empty (DMA buffers are cacheable, remember to maintain D-Cache)."
#endif

#endif /* __has_include("mem_sections.h") */

#else

/* D-Cache feature macro not enabled: BSP_I2C_DMA_SEC does nothing. */
#define BSP_I2C_DMA_SEC

#endif /* OMNIX_FEATURE_MPU_DCACHE */

/* ----------------------------------------------------------------------
 * BSP I2C status.
 * -------------------------------------------------------------------- */
typedef enum
{
    BSP_I2C_OK = 0,
    BSP_I2C_ERROR,
    BSP_I2C_BUSY,
    BSP_I2C_INVALID_PARAM
} bsp_i2c_status_t;

/* ----------------------------------------------------------------------
 * I2C bus ID.
 *
 * Add more buses here when needed.
 * -------------------------------------------------------------------- */
typedef enum
{
    BSP_I2C_BUS_4 = 0,   /* Currently only I2C4 is used */
    BSP_I2C_BUS_MAX
} bsp_i2c_bus_id_t;

/* Forward declaration */
struct bsp_i2c_bus;

/* ----------------------------------------------------------------------
 * I2C device handle.
 *
 * Each I2C slave device on a bus should have one instance of this struct.
 * Upper-layer drivers should NOT access hi2c directly.
 * -------------------------------------------------------------------- */
typedef struct
{
    struct bsp_i2c_bus *bus;  /* Pointer to underlying I2C bus.            */
    uint16_t            addr_7bit;  /* 7-bit address (without R/W bit).    */

    /* Optional config fields for future use */
    uint32_t            max_speed_hz; /* 0 = use HAL configuration.        */
    uint32_t            flags;        /* Reserved (10-bit addr, etc.).     */
} bsp_i2c_device_t;

/**
 * @brief I2C transfer complete callback type.
 *
 * @param dev       Pointer to I2C device.
 * @param user_ctx  User context pointer passed to transfer API.
 * @param status    Final status of the transfer.
 */
typedef void (*bsp_i2c_callback_t)(bsp_i2c_device_t *dev,
                                   void *user_ctx,
                                   bsp_i2c_status_t status);

/* ----------------------------------------------------------------------
 * Public APIs.
 * -------------------------------------------------------------------- */

/**
 * @brief Initialize all I2C buses managed by BSP.
 *
 * This function should be called AFTER MX_I2C4_Init() and MX_BDMA_Init()
 * generated by CubeMX, so that HAL handles and DMA/BDMA are ready.
 */
void bsp_i2c_init(void);

/**
 * @brief Initialize an I2C device on a given bus.
 *
 * @param dev        Pointer to device struct (allocated by caller).
 * @param bus_id     Bus ID (e.g. BSP_I2C_BUS_4).
 * @param addr_7bit  7-bit address of the device (without R/W bit).
 *
 * @return BSP_I2C_OK on success or error code otherwise.
 */
bsp_i2c_status_t bsp_i2c_device_init(bsp_i2c_device_t *dev,
                                     bsp_i2c_bus_id_t bus_id,
                                     uint16_t addr_7bit);

/**
 * @brief Start an async master transmit using DMA.
 *
 * This function is NON-BLOCKING. When transfer finishes, the callback
 * will be called from HAL I2C IRQ context.
 *
 * NOTE ON D-CACHE:
 *   - If D-Cache is enabled and you do NOT use BSP_I2C_DMA_SEC on buffers,
 *     you must ensure proper cache maintenance outside this function.
 *   - If you use static buffers tagged with BSP_I2C_DMA_SEC, they will be
 *     placed into non-cacheable region (when mem_sections.h is present).
 *
 * @param dev       I2C device handle.
 * @param tx_buf    Transmit buffer pointer.
 * @param len       Number of bytes to send.
 * @param cb        Callback when transfer completes (can be NULL).
 * @param user_ctx  User context pointer passed to callback.
 */
bsp_i2c_status_t bsp_i2c_master_transmit(bsp_i2c_device_t *dev,
                                         const uint8_t *tx_buf,
                                         size_t len,
                                         bsp_i2c_callback_t cb,
                                         void *user_ctx);

/**
 * @brief Start an async master receive using DMA.
 *
 * @param dev       I2C device handle.
 * @param rx_buf    Receive buffer pointer.
 * @param len       Number of bytes to receive.
 * @param cb        Callback when transfer completes (can be NULL).
 * @param user_ctx  User context pointer passed to callback.
 */
bsp_i2c_status_t bsp_i2c_master_receive(bsp_i2c_device_t *dev,
                                        uint8_t *rx_buf,
                                        size_t len,
                                        bsp_i2c_callback_t cb,
                                        void *user_ctx);

/**
 * @brief Start an async memory read (e.g. register read) using DMA.
 *
 * Typical pattern for IMU / sensors: write register address then read len bytes.
 *
 * @param dev           I2C device handle.
 * @param mem_addr      Register/memory address in the slave.
 * @param mem_addr_size I2C_MEMADD_SIZE_8BIT or I2C_MEMADD_SIZE_16BIT.
 * @param rx_buf        Receive buffer pointer.
 * @param len           Number of bytes to read.
 * @param cb            Callback when transfer completes (can be NULL).
 * @param user_ctx      User context pointer passed to callback.
 */
bsp_i2c_status_t bsp_i2c_mem_read(bsp_i2c_device_t *dev,
                                  uint16_t mem_addr,
                                  uint16_t mem_addr_size,
                                  uint8_t *rx_buf,
                                  size_t len,
                                  bsp_i2c_callback_t cb,
                                  void *user_ctx);

/**
 * @brief Start an async memory write using DMA.
 *
 * @param dev           I2C device handle.
 * @param mem_addr      Register/memory address in the slave.
 * @param mem_addr_size I2C_MEMADD_SIZE_8BIT or I2C_MEMADD_SIZE_16BIT.
 * @param tx_buf        Transmit buffer pointer.
 * @param len           Number of bytes to write.
 * @param cb            Callback when transfer completes (can be NULL).
 * @param user_ctx      User context pointer passed to callback.
 */
bsp_i2c_status_t bsp_i2c_mem_write(bsp_i2c_device_t *dev,
                                   uint16_t mem_addr,
                                   uint16_t mem_addr_size,
                                   const uint8_t *tx_buf,
                                   size_t len,
                                   bsp_i2c_callback_t cb,
                                   void *user_ctx);

/**
 * @brief Blocking wait for the current transfer on this device to complete.
 *
 * @param dev        I2C device handle.
 * @param timeout_ms Timeout in milliseconds.
 *
 * @return BSP_I2C_OK when completed,
 *         BSP_I2C_BUSY when timeout,
 *         or other error codes on failure.
 */
bsp_i2c_status_t bsp_i2c_wait_complete(bsp_i2c_device_t *dev,
                                       uint32_t timeout_ms);

/**
 * @brief Check if the bus used by this device is currently busy.
 */
bsp_i2c_status_t bsp_i2c_is_bus_busy(const bsp_i2c_device_t *dev);

/* ==== For future extension ============================================
 * If later you want more features (10-bit address, SMBus etc.),
 * extend bsp_i2c_device_t::flags and add new APIs.
 * ====================================================================== */

#ifdef __cplusplus
}
#endif

#endif // H723VG_V2_FREERTOS_BSP_I2C_H