//
// Created by sirin on 2025/11/30.
//
//
// Created by sirin on 2025/11/30.
//
#include "bsp_i2c.h"

/* ----------------------------------------------------------------------
 * External HAL handles generated by CubeMX.
 * Make sure these names match your project.
 * -------------------------------------------------------------------- */
extern I2C_HandleTypeDef hi2c4;

/* ----------------------------------------------------------------------
 * Internal bus structure.
 * -------------------------------------------------------------------- */
typedef enum
{
    BSP_I2C_XFER_IDLE = 0,
    BSP_I2C_XFER_BUSY
} bsp_i2c_xfer_state_t;

typedef enum
{
    BSP_I2C_XFER_TYPE_NONE = 0,
    BSP_I2C_XFER_TYPE_TX,
    BSP_I2C_XFER_TYPE_RX,
    BSP_I2C_XFER_TYPE_MEM_TX,
    BSP_I2C_XFER_TYPE_MEM_RX,
} bsp_i2c_xfer_type_t;

typedef struct bsp_i2c_bus
{
    I2C_HandleTypeDef       *hi2c;

    volatile bsp_i2c_xfer_state_t state;
    volatile bsp_i2c_xfer_type_t  xfer_type;

    bsp_i2c_device_t        *current_dev;
    bsp_i2c_callback_t       current_cb;
    void                    *current_cb_ctx;

    /* For MEM transfers we keep register info here */
    uint16_t                 mem_addr;
    uint16_t                 mem_addr_size;
} bsp_i2c_bus_t;

/* ----------------------------------------------------------------------
 * Global bus table.
 * Later you can append I2C1, I2C2, ... here.
 * -------------------------------------------------------------------- */
static bsp_i2c_bus_t s_i2c_buses[BSP_I2C_BUS_MAX] = {
    [BSP_I2C_BUS_4] =
    {
        .hi2c         = &hi2c4,
        .state        = BSP_I2C_XFER_IDLE,
        .xfer_type    = BSP_I2C_XFER_TYPE_NONE,
        .current_dev  = NULL,
        .current_cb   = NULL,
        .current_cb_ctx = NULL,
        .mem_addr     = 0,
        .mem_addr_size = 0,
    }
};

/* ----------------------------------------------------------------------
 * Local helpers.
 * -------------------------------------------------------------------- */

/**
 * @brief Get bus pointer by ID.
 */
static bsp_i2c_bus_t *bsp_i2c_get_bus_by_id(bsp_i2c_bus_id_t id)
{
    if (id >= BSP_I2C_BUS_MAX)
    {
        return NULL;
    }
    return &s_i2c_buses[id];
}

/**
 * @brief Get bus pointer by HAL I2C handle.
 *
 * Used in HAL callbacks to find which bus triggered the IRQ.
 */
static bsp_i2c_bus_t *bsp_i2c_get_bus_by_handle(I2C_HandleTypeDef *hi2c)
{
    for (int i = 0; i < BSP_I2C_BUS_MAX; ++i)
    {
        if (s_i2c_buses[i].hi2c == hi2c)
        {
            return &s_i2c_buses[i];
        }
    }
    return NULL;
}

/* ----------------------------------------------------------------------
 * Public APIs.
 * -------------------------------------------------------------------- */

void bsp_i2c_init(void)
{
    /*
     * No special runtime configuration for now.
     * Just reset states. HAL I2C init (MX_I2C4_Init) must be called before.
     */
    for (int i = 0; i < BSP_I2C_BUS_MAX; ++i)
    {
        s_i2c_buses[i].state = BSP_I2C_XFER_IDLE;
        s_i2c_buses[i].xfer_type = BSP_I2C_XFER_TYPE_NONE;
        s_i2c_buses[i].current_dev = NULL;
        s_i2c_buses[i].current_cb = NULL;
        s_i2c_buses[i].current_cb_ctx = NULL;
        s_i2c_buses[i].mem_addr = 0;
        s_i2c_buses[i].mem_addr_size = 0;
    }
}

bsp_i2c_status_t bsp_i2c_device_init(bsp_i2c_device_t *dev,
                                     bsp_i2c_bus_id_t bus_id,
                                     uint16_t addr_7bit)
{
    if (dev == NULL)
    {
        return BSP_I2C_INVALID_PARAM;
    }

    bsp_i2c_bus_t *bus = bsp_i2c_get_bus_by_id(bus_id);
    if (bus == NULL || bus->hi2c == NULL)
    {
        return BSP_I2C_ERROR;
    }

    dev->bus = bus;
    dev->addr_7bit = addr_7bit & 0x7F;

    /* Default config, can be overridden by upper layer if needed */
    dev->max_speed_hz = 0;   /* 0 = use HAL config */
    dev->flags = 0;          /* Reserved for future use */

    return BSP_I2C_OK;
}

/**
 * @brief Non-blocking master transmit using DMA/IT (here using HAL DMA if enabled, else IT).
 */
bsp_i2c_status_t bsp_i2c_master_transmit(bsp_i2c_device_t *dev,
                                         const uint8_t *tx_buf,
                                         size_t len,
                                         bsp_i2c_callback_t cb,
                                         void *user_ctx)
{
    if (dev == NULL || dev->bus == NULL || tx_buf == NULL || len == 0U)
    {
        return BSP_I2C_INVALID_PARAM;
    }

    bsp_i2c_bus_t *bus = dev->bus;

    if (bus->state == BSP_I2C_XFER_BUSY)
    {
        return BSP_I2C_BUSY;
    }

    bus->state = BSP_I2C_XFER_BUSY;
    bus->xfer_type = BSP_I2C_XFER_TYPE_TX;
    bus->current_dev = dev;
    bus->current_cb = cb;
    bus->current_cb_ctx = user_ctx;

    HAL_StatusTypeDef hal_ret;

#if (USE_HAL_I2C_REGISTER_CALLBACKS == 1) || defined(I2C4) /* Just a placeholder branch */
    /* Use DMA if enabled in CubeMX, otherwise IT. You can tweak this as needed. */
    hal_ret = HAL_I2C_Master_Transmit_DMA(bus->hi2c,
                                          (uint16_t)(dev->addr_7bit << 1),
                                          (uint8_t *)tx_buf,
                                          (uint16_t)len);
#else
    hal_ret = HAL_I2C_Master_Transmit_IT(bus->hi2c,
                                         (uint16_t)(dev->addr_7bit << 1),
                                         (uint8_t *)tx_buf,
                                         (uint16_t)len);
#endif

    if (hal_ret != HAL_OK)
    {
        bus->state = BSP_I2C_XFER_IDLE;
        bus->xfer_type = BSP_I2C_XFER_TYPE_NONE;
        bus->current_dev = NULL;
        bus->current_cb = NULL;
        bus->current_cb_ctx = NULL;
        return BSP_I2C_ERROR;
    }

    return BSP_I2C_OK;
}

/**
 * @brief Non-blocking master receive using DMA/IT.
 */
bsp_i2c_status_t bsp_i2c_master_receive(bsp_i2c_device_t *dev,
                                        uint8_t *rx_buf,
                                        size_t len,
                                        bsp_i2c_callback_t cb,
                                        void *user_ctx)
{
    if (dev == NULL || dev->bus == NULL || rx_buf == NULL || len == 0U)
    {
        return BSP_I2C_INVALID_PARAM;
    }

    bsp_i2c_bus_t *bus = dev->bus;

    if (bus->state == BSP_I2C_XFER_BUSY)
    {
        return BSP_I2C_BUSY;
    }

    bus->state = BSP_I2C_XFER_BUSY;
    bus->xfer_type = BSP_I2C_XFER_TYPE_RX;
    bus->current_dev = dev;
    bus->current_cb = cb;
    bus->current_cb_ctx = user_ctx;

    HAL_StatusTypeDef hal_ret;

#if (USE_HAL_I2C_REGISTER_CALLBACKS == 1) || defined(I2C4)
    hal_ret = HAL_I2C_Master_Receive_DMA(bus->hi2c,
                                         (uint16_t)(dev->addr_7bit << 1),
                                         rx_buf,
                                         (uint16_t)len);
#else
    hal_ret = HAL_I2C_Master_Receive_IT(bus->hi2c,
                                        (uint16_t)(dev->addr_7bit << 1),
                                        rx_buf,
                                        (uint16_t)len);
#endif

    if (hal_ret != HAL_OK)
    {
        bus->state = BSP_I2C_XFER_IDLE;
        bus->xfer_type = BSP_I2C_XFER_TYPE_NONE;
        bus->current_dev = NULL;
        bus->current_cb = NULL;
        bus->current_cb_ctx = NULL;
        return BSP_I2C_ERROR;
    }

    return BSP_I2C_OK;
}

/**
 * @brief Non-blocking memory read: typical register read (e.g. IMU, EEPROM).
 */
bsp_i2c_status_t bsp_i2c_mem_read(bsp_i2c_device_t *dev,
                                  uint16_t mem_addr,
                                  uint16_t mem_addr_size,
                                  uint8_t *rx_buf,
                                  size_t len,
                                  bsp_i2c_callback_t cb,
                                  void *user_ctx)
{
    if (dev == NULL || dev->bus == NULL || rx_buf == NULL || len == 0U)
    {
        return BSP_I2C_INVALID_PARAM;
    }

    if (mem_addr_size != I2C_MEMADD_SIZE_8BIT &&
        mem_addr_size != I2C_MEMADD_SIZE_16BIT)
    {
        return BSP_I2C_INVALID_PARAM;
    }

    bsp_i2c_bus_t *bus = dev->bus;

    if (bus->state == BSP_I2C_XFER_BUSY)
    {
        return BSP_I2C_BUSY;
    }

    bus->state = BSP_I2C_XFER_BUSY;
    bus->xfer_type = BSP_I2C_XFER_TYPE_MEM_RX;
    bus->current_dev = dev;
    bus->current_cb = cb;
    bus->current_cb_ctx = user_ctx;
    bus->mem_addr = mem_addr;
    bus->mem_addr_size = mem_addr_size;

    HAL_StatusTypeDef hal_ret;

#if (USE_HAL_I2C_REGISTER_CALLBACKS == 1) || defined(I2C4)
    // hal_ret = HAL_I2C_Mem_Read_DMA(bus->hi2c,
    //                                (uint16_t)(dev->addr_7bit << 1),
    //                                mem_addr,
    //                                mem_addr_size,
    //                                rx_buf,
    //                                (uint16_t)len);

    hal_ret = HAL_I2C_Mem_Read(bus->hi2c,
                               (uint16_t)(dev->addr_7bit << 1),
                               mem_addr,
                               mem_addr_size,
                               rx_buf,
                               (uint16_t)len,
                               100);
#else
    hal_ret = HAL_I2C_Mem_Read_IT(bus->hi2c,
                                  (uint16_t)(dev->addr_7bit << 1),
                                  mem_addr,
                                  mem_addr_size,
                                  rx_buf,
                                  (uint16_t)len);
#endif

    if (hal_ret != HAL_OK)
    {
        bus->state = BSP_I2C_XFER_IDLE;
        bus->xfer_type = BSP_I2C_XFER_TYPE_NONE;
        bus->current_dev = NULL;
        bus->current_cb = NULL;
        bus->current_cb_ctx = NULL;
        return BSP_I2C_ERROR;
    }

    return BSP_I2C_OK;
}

/**
 * @brief Non-blocking memory write.
 */
bsp_i2c_status_t bsp_i2c_mem_write(bsp_i2c_device_t *dev,
                                   uint16_t mem_addr,
                                   uint16_t mem_addr_size,
                                   const uint8_t *tx_buf,
                                   size_t len,
                                   bsp_i2c_callback_t cb,
                                   void *user_ctx)
{
    if (dev == NULL || dev->bus == NULL || tx_buf == NULL || len == 0U)
    {
        return BSP_I2C_INVALID_PARAM;
    }

    if (mem_addr_size != I2C_MEMADD_SIZE_8BIT &&
        mem_addr_size != I2C_MEMADD_SIZE_16BIT)
    {
        return BSP_I2C_INVALID_PARAM;
    }

    bsp_i2c_bus_t *bus = dev->bus;

    if (bus->state == BSP_I2C_XFER_BUSY)
    {
        return BSP_I2C_BUSY;
    }

    bus->state = BSP_I2C_XFER_BUSY;
    bus->xfer_type = BSP_I2C_XFER_TYPE_MEM_TX;
    bus->current_dev = dev;
    bus->current_cb = cb;
    bus->current_cb_ctx = user_ctx;
    bus->mem_addr = mem_addr;
    bus->mem_addr_size = mem_addr_size;

    HAL_StatusTypeDef hal_ret;

#if (USE_HAL_I2C_REGISTER_CALLBACKS == 1) || defined(I2C4)
    // hal_ret = HAL_I2C_Mem_Write_DMA(bus->hi2c,
    //                                 (uint16_t)(dev->addr_7bit << 1),
    //                                 mem_addr,
    //                                 mem_addr_size,
    //                                 (uint8_t *)tx_buf,
    //                                 (uint16_t)len);
    hal_ret = HAL_I2C_Mem_Write(bus->hi2c,
                                (uint16_t)(dev->addr_7bit << 1),
                                mem_addr,
                                mem_addr_size,
                                (uint8_t *)tx_buf,
                                (uint16_t)len,100);
#else
    hal_ret = HAL_I2C_Mem_Write_IT(bus->hi2c,
                                   (uint16_t)(dev->addr_7bit << 1),
                                   mem_addr,
                                   mem_addr_size,
                                   (uint8_t *)tx_buf,
                                   (uint16_t)len);
#endif

    if (hal_ret != HAL_OK)
    {
        bus->state = BSP_I2C_XFER_IDLE;
        bus->xfer_type = BSP_I2C_XFER_TYPE_NONE;
        bus->current_dev = NULL;
        bus->current_cb = NULL;
        bus->current_cb_ctx = NULL;
        return BSP_I2C_ERROR;
    }

    return BSP_I2C_OK;
}

/**
 * @brief Blocking wrapper for non-blocking APIs.
 */
bsp_i2c_status_t bsp_i2c_wait_complete(bsp_i2c_device_t *dev,
                                       uint32_t timeout_ms)
{
    if (dev == NULL || dev->bus == NULL)
    {
        return BSP_I2C_INVALID_PARAM;
    }

    bsp_i2c_bus_t *bus = dev->bus;
    uint32_t start = HAL_GetTick();

    while (bus->state == BSP_I2C_XFER_BUSY)
    {
        if ((HAL_GetTick() - start) > timeout_ms)
        {
            (void)HAL_I2C_Master_Abort_IT(bus->hi2c, (uint16_t)(dev->addr_7bit << 1));
            bus->state = BSP_I2C_XFER_IDLE;
            bus->xfer_type = BSP_I2C_XFER_TYPE_NONE;
            bus->current_dev = NULL;
            bus->current_cb = NULL;
            bus->current_cb_ctx = NULL;
            return BSP_I2C_BUSY;
        }
    }

    return BSP_I2C_OK;
}

bsp_i2c_status_t bsp_i2c_is_bus_busy(const bsp_i2c_device_t *dev)
{
    if (dev == NULL || dev->bus == NULL)
    {
        return BSP_I2C_INVALID_PARAM;
    }

    return (dev->bus->state == BSP_I2C_XFER_BUSY) ? BSP_I2C_BUSY : BSP_I2C_OK;
}

/* ----------------------------------------------------------------------
 * HAL callbacks.
 *
 * These callbacks are called from HAL I2C IRQ context.
 * We translate them to BSP-level logic and then call user callbacks.
 * -------------------------------------------------------------------- */

static void bsp_i2c_on_complete(I2C_HandleTypeDef *hi2c, bsp_i2c_status_t status)
{
    bsp_i2c_bus_t *bus = bsp_i2c_get_bus_by_handle(hi2c);
    if (bus == NULL)
    {
        return;
    }

    bsp_i2c_device_t *dev = bus->current_dev;
    bsp_i2c_callback_t cb = bus->current_cb;
    void *ctx = bus->current_cb_ctx;

    bus->state = BSP_I2C_XFER_IDLE;
    bus->xfer_type = BSP_I2C_XFER_TYPE_NONE;
    bus->current_dev = NULL;
    bus->current_cb = NULL;
    bus->current_cb_ctx = NULL;
    bus->mem_addr = 0;
    bus->mem_addr_size = 0;

    if (cb != NULL && dev != NULL)
    {
        cb(dev, ctx, status);
    }
}

void HAL_I2C_MasterTxCpltCallback(I2C_HandleTypeDef *hi2c)
{
    bsp_i2c_on_complete(hi2c, BSP_I2C_OK);
}

void HAL_I2C_MasterRxCpltCallback(I2C_HandleTypeDef *hi2c)
{
    bsp_i2c_on_complete(hi2c, BSP_I2C_OK);
}

void HAL_I2C_MemTxCpltCallback(I2C_HandleTypeDef *hi2c)
{
    bsp_i2c_on_complete(hi2c, BSP_I2C_OK);
}

void HAL_I2C_MemRxCpltCallback(I2C_HandleTypeDef *hi2c)
{
    bsp_i2c_on_complete(hi2c, BSP_I2C_OK);
}

void HAL_I2C_ErrorCallback(I2C_HandleTypeDef *hi2c)
{
    bsp_i2c_on_complete(hi2c, BSP_I2C_ERROR);
}