//
// Created by 马珩桀 on 2026/1/4.
//

#ifndef H723VG_V2_FREERTOS_SWERVE_LIB_POWER_CONTROL_H
#define H723VG_V2_FREERTOS_SWERVE_LIB_POWER_CONTROL_H

#endif //H723VG_V2_FREERTOS_SWERVE_LIB_POWER_CONTROL_H